name: downloads
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  ingest_downloads:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    
    - name: pip packages
      run: pip install tinybird-cli
    
    - name: version
      run: tb --version

      
    - name: ingest-previous-day
      run: export NOW=`date +"%Y%m%d"` && export NOWTB=`date +"%Y-%m-%d"` && export DDATE=`date --date="$NOW -$DAY day" +%Y%m%d` && export DDATETB=`date --date="$NOWTB -$DAY day" +%Y-%m-%d` && tb --token $TOKEN --gcp-project-id $PROJECT_ID --gcs-bucket $BUCKET datasource append $DATASOURCE --connector bigquery --sql "SELECT timestamp_trunc(timestamp, hour) as timestamp, country_code, file.project as project, file.version as version, details.python as python, details.system.name as system_name, count(*) as downloads FROM \`the-psf.pypi.downloads$DDATE\` WHERE timestamp > '$DDATETB 12:00:00' group by timestamp, country_code, project, version, python, system_name"
      env:
        TOKEN: ${{ secrets.TB_TOKEN }}
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        BUCKET: ${{ secrets.GCP_BUCKET_TEMP }}
        DATASOURCE: file_downloads__v1
        DAY: 1

