name: metadata
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  ingest_metadata:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: stddevco
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true
    - name: pip packages
      run: pip install tinybird-cli
    
    - name: version
      run: tb --version

    - name: ingest-data
      run: tb --token $TOKEN --gcp-project-id $PROJECT_ID --gcs-bucket $BUCKET datasource replace $DATASOURCE --connector bigquery --sql "SELECT * FROM \`stddevco.tinybird.agents\`"
      env:
        TOKEN: ${{ secrets.TB_TOKEN }}
        PROJECT_ID: stddevco
        BUCKET: alrocar
        DATASOURCE: agents
